### ISSUE TITLE
Hooks MGCopyAnswer on iOS 10.3.3 32-bit

### ISSUE THREAD

**Issue by iThanh** [PoomSmart/PanoEnabler#3]
Thank you for your sharing!
When I Hooks MGCopyAnswer on iOS 10.3.3 32-bit I got some errors.
How I can do this on iOS 10.3.3, please?

**Comment by PoomSmart** [comment]
Instead mess around with `/var/mobile/Library/Caches/com.apple.MobileGestalt.plist`.
[A Stackoverflow that talks about this issue](https://stackoverflow.com/questions/37903788/libmobilegestalt-dylib-crashed-when-hooking-mgcopyanswer-for-arm64).

**Comment by iThanh** [comment]
Thank you,
I follow with contents on stackoverflow.
I hooks MGCopyAnswer but I got Safe mode.
But I try Hooks MGGetBoolAnswer it work normal.
Please!
